name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install ARM64 Dependencies
      run: sudo apt install g++-aarch64-linux-gnu

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Configure CMake (ARM64)
      run: cmake -B ${{github.workspace}}/buildarm64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Build (ARM64)
      run: cmake --build ${{github.workspace}}/buildarm64 --config ${{env.BUILD_TYPE}}
      
    - name: Gzip Binaries
      run: tar -cvzf ${{github.workspace}}/build/BlazeEncryptionsx86_64.tar.gz ${{github.workspace}}/build/BlazeEncryptions && tar -cvzf ${{github.workspace}}/buildarm64/BlazeEncryptionsaarch64.tar.gz ${{github.workspace}}/buildarm64/BlazeEncryptions

    - uses: actions/upload-artifact@v3.1.1
      with :
        name: Upload Builds
        path: ${{github.workspace}}/build/BlazeEncryptionsx86_64.tar.gz ${{github.workspace}}/buildarm64/BlazeEncryptionsaarch64.tar.gz

